/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-12-18 07:29:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/sdedu/Desktop/SPRING_CODES/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KMS_PROJECT_YESFUTURE/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1733282290650L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>예스 퓨처~</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"menu-bar\">\r\n");
      out.write("        <!-- 이 위치에 main으로 가는 버튼 만들기 -->\r\n");
      out.write("        <a href=\"problemMain\" class=\"group1\"><input type=\"button\" value=\"문제은행 가기\"></a>\r\n");
      out.write("        <a href=\"boardMain\" class=\"group1\"><input type=\"button\" value=\"게시판\"></a>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"group2\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 가로 경계선 -->\r\n");
      out.write("    <hr class=\"divider\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 메인 레이아웃 -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- 왼쪽 메뉴 영역 -->\r\n");
      out.write("        <div class=\"left-menu\">\r\n");
      out.write("            <button id=\"question\">질문</button>\r\n");
      out.write("            <button id=\"free\">자유</button>\r\n");
      out.write("            <button id=\"propose\">건의</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 오른쪽 게시판 영역 -->\r\n");
      out.write("        <div class=\"right-board\" id=\"board-content\">\r\n");
      out.write("            <div class=\"board-title\">게시판</div>\r\n");
      out.write("            <!-- 비동기 통신으로 불러올 데이터 -->\r\n");
      out.write("            <p>여기에 게시판 내용이 표시됩니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    	/* 경계선 스타일 */\r\n");
      out.write("        .divider {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-top: 1px solid #000; /* 얇은 검은색 선 */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 메뉴바 스타일 */\r\n");
      out.write("        .menu-bar {\r\n");
      out.write("            display: flex; /* Flexbox 적용 */\r\n");
      out.write("            justify-content: flex-start; /* 왼쪽부터 가로로 배치 */\r\n");
      out.write("            align-items: center; /* 세로 중앙 정렬 */\r\n");
      out.write("            padding: 10px 20px; /* 메뉴바 안쪽 여백 */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 좌측 버튼 스타일 */\r\n");
      out.write("		.group1 {\r\n");
      out.write("		    display: flex;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 우측 버튼 그룹 스타일 */\r\n");
      out.write("		.group2 {\r\n");
      out.write("		    display: flex;\r\n");
      out.write("		    margin-left: auto; /* 우측으로 밀어붙임 */\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("        /* 버튼 사이의 간격 설정 */\r\n");
      out.write("        .menu-bar a {\r\n");
      out.write("            margin-right: 20px; /* 각 버튼 사이의 간격 (원하는 값으로 조정 가능) */\r\n");
      out.write("            text-decoration: none; /* 링크 밑줄 제거 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 버튼 스타일 (옵션) */\r\n");
      out.write("        input[type=\"button\"] {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 특정 value (닉네임 버튼)에 스타일 적용 */\r\n");
      out.write("    	input[type=\"button\"][value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.memberNickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"] {\r\n");
      out.write("        background-color: transparent; /* 배경을 투명하게 설정 */\r\n");
      out.write("        color: #4CAF50; /* 글자 색상 설정 */\r\n");
      out.write("        border: 1px solid #4CAF50; /* 선택사항: 테두리 추가 */\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("        /* 버튼에 마우스를 올렸을 때 스타일 (옵션) */\r\n");
      out.write("        input[type=\"button\"]:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 전체 레이아웃 */\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 80vh; /* 화면 높이의 80%를 사용 */\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 왼쪽 메뉴 영역 */\r\n");
      out.write("        .left-menu {\r\n");
      out.write("            flex: 1; /* 1:4 비율 중 1 */\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center; /* 버튼을 중앙 정렬 */\r\n");
      out.write("            border-right: 1px solid black; /* 세로 구분선 */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 버튼 스타일 */\r\n");
      out.write("        .left-menu button {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .left-menu button:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 오른쪽 게시판 출력 영역 */\r\n");
      out.write("        .right-board {\r\n");
      out.write("            flex: 4; /* 1:4 비율 중 4 */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            overflow-y: auto; /* 내용이 넘칠 경우 스크롤 */\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 게시판 제목 스타일 */\r\n");
      out.write("        .board-title {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border-bottom: 2px solid #000;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    //    document.getElementById(\"question\").addEventListener(\"click\", function() {\r\n");
      out.write("    //    });\r\n");
      out.write("    //    document.getElementById(\"free\").addEventListener(\"click\", function() {\r\n");
      out.write("    //    });\r\n");
      out.write("    //    document.getElementById(\"propose\").addEventListener(\"click\", function() {\r\n");
      out.write("    //    });\r\n");
      out.write("    </script>\r\n");
      out.write("	    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/boardMain.jsp(19,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.memberEmail }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<!-- 회원 가입 버튼 -->\r\n");
          out.write("		    <a href=\"agree\"><input type=\"button\" value=\"회원 가입\"></a>\r\n");
          out.write("		    <!-- 로그인 버튼 -->\r\n");
          out.write("		    <a href=\"login\"><input type=\"button\" value=\"로그인\"></a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/boardMain.jsp(26,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.memberEmail }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"mypage\"><input type=\"button\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.memberNickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></a>\r\n");
          out.write("			<a href=\"logout\"><input type=\"button\" value=\"로그아웃\"></a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
